name: Build-and-Test
on:
 push:
  branches: [main]
 pull_request:
  branches: [main]
jobs:
 build:
  env:
   configuration: release
  runs-on: ubuntu-latest
  steps:
  - name: checkout resources
    uses: actions/checkout@v2
  - name: Setup .Net
    uses: actions/setup-dotnet@v1
    with:
     dotnet-version: 6.0.x
  - name: restore dependencies
    run: dotnet restore
  - name: build
    run: dotnet build --no-restore --configuration ${{ env.configuration }}
  - name: test
    run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
  - name: publish
    run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp}}/artifact
  - name: upload the build artifact
    uses: actions/upload-artifact@v2.2.4
    with:
     name: publish
     path: ${{runner.temp}}/artifact
